module.exports = {
    DB_ERROR_CREATE: `DB_INTERNAL_ERROR: "CREATE" RELATED OPERATION FAILED CODE: `,
    DB_ERROR_UPDATE: `DB_INTERNAL_ERROR: "UPDATE" RELATED OPERATION FAILED CODE: `,
    DB_ERROR_SELECT: `DB_INTERNAL_ERROR: "SELECT" RELATED OPERATION FAILED CODE: `,
    DB_ERROR_DELETE: `DB_INTERNAL_ERROR: "DELETE" RELATED OPERATION FAILED CODE: `,
    AUTH_ERROR_TOKEN: `AUTH_TOKEN_ERROR CODE:`,
    AUTH_ERROR_PASSWORD: `AUTH_PASSWORD_ERROR CODE:`,
    SESSION_ERROR_DESTROY: `ESSION_DESTROY_ERROR CODE:`,
};